resume_from_checkpoint_path: null 
result_path: "./result"
pretrained_model_name_or_path: null
dataset_name_or_paths: ["/public/home/xlwang2/codes/LLM-document/data/cache/synthdog-zh-v1/"] # should be prepared from https://github.com/beacandler/EATEN
sort_json_key: True
train_batch_sizes: [4]
val_batch_sizes: [1]
input_size: [960, 1280]
max_length: 256
align_long_axis: False
num_nodes: 1
seed: 2022
lr: 5e-5
warmup_steps: 2000
num_training_samples_per_epoch: 500000
max_epochs: 10
max_steps: -1
num_workers: 1
val_check_interval: 1.0
check_val_every_n_epoch: 1
gradient_clip_val: 1.0
verbose: True
